modLoader="javafml"
loaderVersion="[35,)"
license="BSD-3-Clause License"
[[mods]]
modId="watersource"
version="${file.jarVersion}"
displayName="Water Source"
credits="Lemon Slice Studio, Geolykt"
authors="Gloridifice"
logoFile="watersource.png"
description='''
This is a mod added a Thirst and Drinking System to Minecraft.
'''
[[dependencies.watersource]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.watersource]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
